name: machine_learning_cookbook
channels:
  - defaults
dependencies:
  - _nb_ext_conf=0.4.0=py36_1
  - _tflow_1100_select=0.0.2=eigen
  - absl-py=0.4.0=py36h28b3542_0
  - anaconda-client=1.7.1=py36_0
  - appdirs=1.4.3=py36h28b3542_0
  - appnope=0.1.0=py36hf537a9a_0
  - asn1crypto=0.24.0=py36_0
  - astor=0.7.1=py36_0
  - attrs=18.1.0=py36_0
  - automat=0.7.0=py36_0
  - backcall=0.1.0=py36_0
  - blas=1.0=mkl
  - bleach=2.1.4=py36_0
  - ca-certificates=2018.03.07=0
  - certifi=2018.8.24=py36_1
  - cffi=1.11.5=py36h342bebf_0
  - chardet=3.0.4=py36_1
  - clyent=1.2.2=py36_1
  - constantly=15.1.0=py36h28b3542_0
  - cryptography=2.3.1=py36hdbc3d79_0
  - cycler=0.10.0=py36hfc81398_0
  - decorator=4.3.0=py36_0
  - entrypoints=0.2.3=py36_2
  - freetype=2.9.1=hb4e5f40_0
  - gast=0.2.0=py36_0
  - grpcio=1.12.1=py36hd9629dc_0
  - h5py=2.8.0=py36h3c9e6ae_0
  - hdf5=1.10.2=hfa1e0ec_1
  - html5lib=1.0.1=py36_0
  - hyperlink=18.0.0=py36_0
  - idna=2.7=py36_0
  - incremental=17.5.0=py36_0
  - intel-openmp=2018.0.3=0
  - ipykernel=4.8.2=py36_0
  - ipython=6.5.0=py36_0
  - ipython_genutils=0.2.0=py36h241746c_0
  - ipywidgets=7.4.0=py36_0
  - jedi=0.12.1=py36_0
  - jinja2=2.10=py36_0
  - jsonschema=2.6.0=py36hb385e00_0
  - jupyter_client=5.2.3=py36_0
  - jupyter_core=4.4.0=py36_0
  - keras=2.2.2=0
  - keras-applications=1.0.4=py36_1
  - keras-base=2.2.2=py36_0
  - keras-preprocessing=1.0.2=py36_1
  - kiwisolver=1.0.1=py36h0a44026_0
  - libcxx=4.0.1=h579ed51_0
  - libcxxabi=4.0.1=hebd6815_0
  - libedit=3.1.20170329=hb402a30_2
  - libffi=3.2.1=h475c297_4
  - libgfortran=3.0.1=h93005f0_2
  - libpng=1.6.34=he12f830_0
  - libprotobuf=3.6.0=hd9629dc_0
  - libsodium=1.0.16=h3efe00b_0
  - markdown=2.6.11=py36_0
  - markupsafe=1.0=py36h1de35cc_1
  - matplotlib=2.2.3=py36h54f8f79_0
  - mistune=0.8.3=py36h1de35cc_1
  - mkl=2018.0.3=1
  - mkl_fft=1.0.4=py36h5d10147_1
  - mkl_random=1.0.1=py36h5d10147_1
  - nb_anacondacloud=1.4.0=py36_0
  - nb_conda=2.2.1=py36_0
  - nb_conda_kernels=2.1.0=py36_0
  - nbconvert=5.3.1=py36_0
  - nbformat=4.4.0=py36h827af21_0
  - nbpresent=3.0.2=py36_1
  - ncurses=6.1=h0a44026_0
  - notebook=5.6.0=py36_0
  - numpy=1.15.0=py36h648b28d_0
  - numpy-base=1.15.0=py36h8a80b8c_0
  - openssl=1.0.2p=h1de35cc_0
  - pandas=0.23.4=py36h6440ff4_0
  - pandoc=2.2.1=h1a437c5_0
  - pandocfilters=1.4.2=py36_1
  - parso=0.3.1=py36_0
  - patsy=0.5.0=py36_0
  - pexpect=4.6.0=py36_0
  - pickleshare=0.7.4=py36hf512f8e_0
  - pip=10.0.1=py36_0
  - prometheus_client=0.3.1=py36_0
  - prompt_toolkit=1.0.15=py36haeda067_0
  - protobuf=3.6.0=py36h0a44026_0
  - ptyprocess=0.6.0=py36_0
  - pyasn1=0.4.4=py36_0
  - pyasn1-modules=0.2.2=py36_0
  - pycparser=2.18=py36_1
  - pygments=2.2.0=py36h240cd3f_0
  - pyopenssl=18.0.0=py36_0
  - pyparsing=2.2.0=py36_1
  - pysocks=1.6.8=py36_0
  - python=3.6.6=hc167b69_0
  - python-dateutil=2.7.3=py36_0
  - pytz=2018.5=py36_0
  - pyyaml=3.13=py36h1de35cc_0
  - pyzmq=17.1.2=py36h1de35cc_0
  - readline=7.0=hc1231fa_4
  - requests=2.19.1=py36_0
  - scikit-learn=0.19.1=py36hf9f1f73_0
  - scipy=1.1.0=py36hf1f7d93_0
  - seaborn=0.9.0=py36_0
  - send2trash=1.5.0=py36_0
  - service_identity=17.0.0=py36h28b3542_0
  - setuptools=40.0.0=py36_0
  - simplegeneric=0.8.1=py36_2
  - six=1.11.0=py36_1
  - sqlalchemy=1.2.11=py36h1de35cc_0
  - sqlite=3.24.0=ha441bb4_0
  - statsmodels=0.9.0=py36h1d22016_0
  - tensorboard=1.10.0=py36hdc36e2c_0
  - tensorflow=1.10.0=eigen_py36h0906837_0
  - tensorflow-base=1.10.0=eigen_py36h4f0eeca_0
  - termcolor=1.1.0=py36_1
  - terminado=0.8.1=py36_1
  - testpath=0.3.1=py36h625a49b_0
  - tk=8.6.7=h35a86e2_3
  - tornado=5.1=py36h1de35cc_0
  - traitlets=4.3.2=py36h65bd3ce_0
  - twisted=17.5.0=py36_0
  - urllib3=1.23=py36_0
  - wcwidth=0.1.7=py36h8c6ec74_0
  - webencodings=0.5.1=py36_1
  - werkzeug=0.14.1=py36_0
  - wheel=0.31.1=py36_0
  - widgetsnbextension=3.4.0=py36_0
  - xlrd=1.1.0=py36_1
  - xz=5.2.4=h1de35cc_4
  - yaml=0.1.7=hc338f04_2
  - zeromq=4.2.5=h0a44026_0
  - zlib=1.2.11=hf3cbc9b_2
  - zope=1.0=py36_0
  - zope.interface=4.5.0=py36h1de35cc_0
  - pip:
    - lifelines==0.14.6
prefix: /Users/f00/anaconda/envs/machine_learning_cookbook

